import Head from 'next/head'
import "animate.css"
import Form from "@/components/form";
import {useRouter} from "next/router";

export default function Home() {
    const router = useRouter()
    const onLoaded = (icao) => {
        router.push(`/airport/${icao}`)
    }

  return (
    <>
      <Head>
        <title>Airport METAR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-grey">
          <div className="h-screen flex justify-center flex-col items-center animate__animated animate__fadeIn">
              <Form
                  onSubmit={onLoaded}
              />
          </div>

      </main>
    </>
  )
}
