import Head from 'next/head'
import "animate.css"
import Form from "@/components/form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Airport METAR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-grey">
          <div className="h-screen flex justify-center flex-col items-center animate__animated animate__fadeIn">
              <Form/>
          </div>

      </main>
    </>
  )
}
