import Head from 'next/head'
import "animate.css"
import Form from "@/components/form";
import {useRouter} from "next/router";
import {useContext, useEffect, useState} from "react";
import {ContextApp} from "@/context/context";
import Loading from "@/components/loading";

export default function Home() {
    const router = useRouter()
    const [airport, metar, setAirportData, setMetar] = useContext(ContextApp)
    const [loading, setLoading] = useState(false)

    const onLoaded = (icao) => {
        router.push(`/airport/${icao}`)
    }
    const handleMetar = data => setMetar(data)
    const handleAirport = data => setAirportData(data)

    useEffect(() => {
        if (airport && metar) onLoaded(airport.icao_code)

    }, [loading])

    return (
        <>
            <Head>
                <title>Airport METAR</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <main className="bg-grey">
                {
                    loading &&
                    <Loading/>
                }
                <div className="h-screen flex justify-center flex-col items-center animate__animated animate__fadeIn">
                    <Form
                        setMetar={handleMetar}
                        setAirport={handleAirport}
                        setLoading={setLoading}
                    />
                </div>

            </main>
        </>
    )
}
